---

- name: Set macOS preferences
  block:
    - name: Quit pref window
      ansible.builtin.command:
        cmd: /usr/bin/osascript -e 'tell application "System Preferences" to quit'
      changed_when: false

    - name: Tap custom repos
      check_mode: false
      community.general.homebrew_tap:
        name: dsully/tap

    - name: Install core formulae
      community.general.homebrew:
        name: macos-defaults
        state: upgraded

    - name: Create temp directory
      ansible.builtin.file:
        path: /tmp/macos-defaults
        state: directory
        mode: '0755'

    - name: Copy yaml files
      ansible.builtin.copy:
        src: macos-defaults
        dest: /tmp/
        mode: '0644'

    - name: Apply defaults
      ansible.builtin.command:
        cmd: "/opt/homebrew/bin/macos-defaults apply /tmp/macos-defaults/"
      changed_when: false

    - name: Unhidden ~/Library
      ansible.builtin.command:
        cmd: /usr/bin/chflags nohidden ~/Library
      changed_when: false

    - name: Copy dictionary files
      ansible.builtin.copy:
        src: "dictionary.plist"
        dest: "{{ ansible_env.HOME }}/Downloads/dictionary.plist"
        mode: '0644'

    - name: Import Shortcuts
      ansible.builtin.command:
        cmd: "/usr/bin/open -a Shortcuts {{ item }}"
      changed_when: false
      loop:
        - https://www.icloud.com/shortcuts/fbd290c7e1c44286a2422f8c17a076ce # はてブする
        - https://www.icloud.com/shortcuts/4ac45afa7bae47e398fce01c6ee4727b # LinkCopy(md)
        - https://www.icloud.com/shortcuts/2056e1323aa0497080a482547707819b # LinkCopy(rtf)

    - name: Open README
      ansible.builtin.import_role:
        name: open_readme
      vars:
        open_readme_rolename: install_macos_config

  always:
    - name: Remove yaml file
      ansible.builtin.file:
        path: /tmp/macos-defaults
        state: absent
