---

- name: Create SSH config directory and target file
  block:
    - name: Create conf directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/ssh"
        state: directory
        mode: '0755'

    - name: Copy config file
      when: not ansible_check_mode
      ansible.builtin.copy:
        src: "{{ misc_create_sshconf_src }}"
        dest: "{{ ansible_env.HOME }}/.config/ssh/{{ misc_create_sshconf_src }}"
        mode: '0644'

    - name: Create config file with template
      when:
        - not ansible_check_mode
        - misc_create_sshconf_src | regex_search('\.j2$')
      ansible.builtin.template:
        src: "{{ misc_create_sshconf_src }}"
        dest: "{{ ansible_env.HOME }}/.config/ssh/{{ misc_create_sshconf_src | regex_replace('\\.j2$', '') }}"
        mode: '0644'
