tap 'homebrew/dupes'
tap 'homebrew/versions'
tap 'homebrew/binary'
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'cloudfoundry/tap'
cask_args appdir: '/Applications'

brew 'ag'
brew 'autoconf'
brew 'bash'
brew 'cf-cli'
brew 'colordiff'
brew 'coreutils'
brew 'ctags'
brew 'curl'
brew 'erlang'
brew 'gettext'
brew 'ghq'
brew 'gibo'
brew 'gist'
brew 'git'
brew 'git-flow-avh'
brew 'gpg2'
brew 'hub'
brew 'imagemagick'
brew 'jpeg'
brew 'jq'
brew 'libevent'
brew 'libpng'
brew 'libxml2'
brew 'libyaml'
brew 'mackup'
brew 'markdown'
brew 'mas'
brew 'mcrypt'
brew 'mercurial'
brew 'mysql', args: ['client-only']
brew 'nkf'
brew 'openssl'
brew 'peco'
brew 'pinentry-mac'
brew 'pkg-config'
brew 'postgres'
brew 'proctools'
brew 'readline'
brew 'rmtrash'
brew 'tig'
brew 'tree'
brew 'vault'
brew 'wget'
brew 'zsh'

cask '0xed'
cask 'adapter'
cask 'adpassmon'
cask 'alfred'
cask 'atom'
cask 'audacity'
cask 'bartender'
cask 'bathyscaphe'
cask 'bettertouchtool'
cask 'betterzipql'
cask 'cheatsheet'
cask 'chefdk'
cask 'citrix-receiver'
cask 'clipy'
cask 'cocoarestclient'
cask 'cyberduck'
cask 'devcenter'
cask 'dmm-player'
cask 'docker'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'flash'
cask 'flip4mac'
cask 'flux'
cask 'font-clear-sans'
cask 'font-fontawesome'
cask 'font-m-plus'
cask 'font-ricty-diminished'
cask 'font-roboto'
cask 'font-source-code-pro'
cask 'gimp'
cask 'github-desktop'
cask 'google-chrome'
cask 'google-drive'
cask 'google-hangouts'
cask 'gpgtools'
cask 'hosts'
cask 'java'
cask 'kafka-tool'
cask 'karabiner'
cask 'kindle'
cask 'licecap'
cask 'parallels-desktop'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'rabbitmq'
cask 'rdm'
cask 'sequel-pro'
cask 'silverlight'
cask 'skitch'
cask 'skype'
cask 'slack'
cask 'sublime-text'
cask 'the-unarchiver'
cask 'virtualbox'
cask 'vagrant'
cask 'vagrant-manager'
cask 'vlc'
cask 'webpquicklook'
cask 'wireshark'
cask 'xerox-print-driver'

mas '1Password', id:443987910
mas 'Airmail 3', id:918858936
mas 'Dash', id:449589707
mas 'Desktop Calendar Plus', id:524688159
mas 'Keynote', id:409183694
mas 'Kobito', id:896624060
mas 'LINE', id:539883307
mas 'Numbers', id:409203825
mas 'OmniFocus', id:867299399
mas 'OmniGraffle', id:711830901
mas 'PDF Outliner', id:420874236
mas 'PopClip', id:445189367
mas 'ReceiptKeeper', id:413449473
mas 'Twitter', id:409789998
mas 'XCode', id:497799835
