---
namespace: legnoh
name: dotfiles
description: my dotfiles
version: "0.1.0"
readme: README.md
authors:
    - Ryoma Kai (https://github.com/legnoh)
license:
    - MIT
tags:
    - dotfiles
    - roles
repository: https://github.com/legnoh/dotfiles
