---

- name: Deploy dotfiles
  hosts: localhost
  roles:
    - role: install_zsh_config
      tags: [install_zsh_config]

    - role: install_ssh_config
      tags: [install_ssh_config]

    - role: install_1password
      tags: [install_1password]

    - role: install_core_brews
      tags: [install_core_brews]

    - role: install_office_casks
      tags: [install_office_casks]

    - role: install_terminal_config
      tags: [install_terminal_config]

    - role: install_private_casks
      tags: [install_private_casks]

    - role: install_git_packages
      tags: [install_git_packages]

    - role: install_starship
      tags: [install_starship]

    - role: install_direnv
      tags: [install_direnv]

    - role: install_raycast
      tags: [install_raycast]

    - role: install_vscode
      tags: [install_vscode]

    - role: install_rancher
      tags: [install_rancher]

    - role: install_bridgecast
      tags: [install_bridgecast]

    - role: install_dell_monitor_driver
      tags: [install_dell_monitor_driver]

    - role: install_logi_options+
      tags: [install_logi_options+]

    - role: install_scansnap
      tags: [install_scansnap]
