---

- name: Deploy dotfiles
  hosts: localhost
  roles:
    - role: install_macos_config
      when: ansible_distribution == 'MacOSX'
      tags: [install_macos_config]

    - role: install_zsh_config
      tags: [install_zsh_config]

    - role: install_ssh_config
      tags: [install_ssh_config]

    - role: install_core_brews
      tags: [install_core_brews]

    - role: install_git_packages
      tags: [install_git_packages]

    - role: install_go
      tags: [install_go]

    - role: install_node
      tags: [install_node]

    - role: install_starship
      tags: [install_starship]

    - role: install_1password
      when: ansible_distribution == 'MacOSX'
      tags: [install_1password, gui]

    - role: install_terminal_config
      when: ansible_distribution == 'MacOSX'
      tags: [install_terminal_config]

    - role: install_office_casks
      when: ansible_distribution == 'MacOSX'
      tags: [install_office_casks, gui]

    - role: install_private_casks
      when: ansible_distribution == 'MacOSX'
      tags: [install_private_casks, gui]

    - role: install_raycast
      when: ansible_distribution == 'MacOSX'
      tags: [install_raycast, gui]

    - role: install_vscode
      when: ansible_distribution == 'MacOSX'
      tags: [install_vscode, gui]

    - role: install_rancher
      when: ansible_distribution == 'MacOSX'
      tags: [install_rancher, gui]

    - role: install_bridgecast
      when: ansible_distribution == 'MacOSX'
      tags: [install_bridgecast, device_driver]

    - role: install_dell_monitor_driver
      when: ansible_distribution == 'MacOSX'
      tags: [install_dell_monitor_driver, device_driver]

    - role: install_logi_options_plus
      when: ansible_distribution == 'MacOSX'
      tags: [install_logi_options_plus, device_driver]

    - role: install_scansnap
      when: ansible_distribution == 'MacOSX'
      tags: [install_scansnap, device_driver]

    - role: uninstall
      when: ansible_distribution == 'MacOSX'
      tags: [never, uninstall]
