---

- name: Install zsh configs
  block:
    - name: Create .hushlogin for omit login prompt
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.hushlogin"
        state: touch
        mode: '0644'

    - name: Install zsh-plugins
      community.general.homebrew:
        name:
          - zsh-autosuggestions
          - zsh-syntax-highlighting
        state: upgraded

    - name: Copy Zsh config files
      ansible.builtin.include_role:
        name: misc_create_zshconf
      vars:
        misc_create_zshconf_src: "{{ item }}"
      loop:
        - alias.zsh
        - history.zsh
        - zsh-autosuggestions.zsh
        - zsh-syntax-highlighting.zsh

    - name: Copy root Zsh config files
      ansible.builtin.copy:
        src: .zshrc
        dest: "{{ ansible_env.HOME }}/.zshrc"
        mode: '0644'
