---

- name: Install starship
  block:
    - name: Install app
      when: not ansible_check_mode
      community.general.homebrew:
        name: starship
        state: upgraded

    - name: Copy config file
      when: not ansible_check_mode
      ansible.builtin.copy:
        src: "starship.toml"
        dest: "{{ ansible_env.HOME }}/.config/starship.toml"
        mode: '0644'

    - name: Copy Zsh config file
      ansible.builtin.import_role:
        name: misc_create_zshconf
      vars:
        misc_create_zshconf_src: starship.zsh
        misc_create_zshconf_cmd: starship init zsh
