---

- name: Install 1Password
  block:
    - name: Install mas-cli
      community.general.homebrew:
        name: mas
        state: upgraded

    - name: Install 1Password & CLI
      community.general.homebrew_cask:
        name:
          - 1password
          - 1password-cli
        state: upgraded

    - name: Install 1 Password for Safari extension
      when: not ansible_check_mode
      community.general.mas:
        id: 1569813296 # 1 Password for Safari
        state: latest

    - name: Copy SSH config file
      ansible.builtin.import_role:
        name: misc_create_sshconf
      vars:
        misc_create_sshconf_src: 1password.conf

    - name: Copy Gitconfig file
      ansible.builtin.import_role:
        name: misc_create_gitconf
      vars:
        misc_create_gitconf_src: 1password.gitconfig

    - name: Open README
      ansible.builtin.import_role:
        name: misc_open_readme
      vars:
        misc_open_readme_rolename: install_1password

    - name: Open App
      ansible.builtin.command:
        cmd: /usr/bin/open -a 1Password
      changed_when: false
