export LANG=ja_JP.UTF-8
export HISTFILE=~/.zsh_history
export HISTSIZE=1000000000000
export SAVEHIST=1000000000000
export PROMPT_COMMAND='history -a; history -r'
export ZPLUG_HOME=/usr/local/opt/zplug
export DOT=$HOME/code/src/github.com/legnoh/dotfiles
export GOPATH=$HOME/code
export RUBY_VERSION=$($HOME/.anyenv/envs/rbenv/bin/rbenv global|sed -E 's/.[0-9]$/.0/g')
export PATH=$HOME/.anyenv/bin:$DOT/bin:/$HOME/.gem/ruby/$RUBY_VERSION/bin:$GOPATH/bin:$PATH

source $ZPLUG_HOME/init.zsh
zstyle ":zplug:tag" depth 1
zstyle ":zplug:tag" defer 2
zplug 'legnoh/materialshell', as:theme, hook-build:"open $ZPLUG_HOME/repos/legnoh/materialshell/materialshell-dark.terminal"
zplug 'felixr/docker-zsh-completion'
zplug 'docker/cli', use:contrib/completion/zsh/_docker
zplug 'docker/compose', use:contrib/completion/zsh/_docker-compose
zplug 'frodenas/bosh-zsh-autocomplete-plugin'
zplug 'legnoh/fly-zsh-autocomplete-plugin'
zplug 'psprint/zsh-navigation-tools'
zplug 'zsh-users/zsh-autosuggestions'
zplug 'zsh-users/zsh-completions'
zplug "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc", from:local
zplug "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc", from:local

alias cflpws='cf login -a api.run.pivotal.io'
alias fll="fly -t l login -c http://127.0.0.1:8080 -b && fly -t l sync && open http://127.0.0.1:8080/"
alias gl="ghq look"
alias gpg="gpg2"
alias ls="ls -alhG"
alias conpose="docker-compose -p concourse -f $DOT/docker/concourse/docker-compose.yml"
alias zclr="rm -rf $ZPLUG_HOME && git clone --depth 1 https://github.com/zplug/zplug.git $ZPLUG_HOME && exec $SHELL -l"

source $HOME/.zshrc.optional
if ! zplug check; then zplug install; fi
eval "$(anyenv init -)" "$(direnv hook zsh)"
zplug load
