autoload -Uz colors && colors
autoload -Uz compinit && compinit -u

export PATH=$HOME/bin:/usr/local/bin:$PATH
export LANG=ja_JP.UTF-8

source ~/.zshrc.plugin
source ~/.zshrc.setting
source ~/.zshrc.alias.internal
source ~/.zshrc.alias.external
source ~/.zshrc.custom.internal
source ~/.zshrc.custom.external
