---

- name: Install ScanSnap
  block:
    - name: Install Rosetta2
      become: true
      ansible.builtin.command:
        cmd: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
      changed_when: false

    - name: Install Scansnap
      community.general.homebrew_cask:
        name: fujitsu-scansnap-home
        state: upgraded
        sudo_password: "{{ install_scansnap_sudo_pass }}"

    - name: Copy profile
      ansible.builtin.copy:
        src: profiles.ssmp
        dest: "{{ ansible_env.HOME }}/Downloads/scansnap-profiles.ssmp"
        mode: '0644'

    - name: Open README
      ansible.builtin.import_role:
        name: misc_open_readme
      vars:
        misc_open_readme_rolename: install_scansnap

    - name: Open Scansnap
      ansible.builtin.command:
        cmd: /usr/bin/open --background -a 'ScanSnapHomeMain'
      changed_when: false
