"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[time]
disabled = false
format = '[\[$time\]]($style) '
style = "normal"
