---

- name: Install BRIDGE CAST app
  block:
    - name: Tap custom repos
      check_mode: false
      community.general.homebrew_tap:
        name: legnoh/etc

    - name: Install BRIDGE CAST.app
      community.general.homebrew_cask:
        name: roland-bridge-cast-app
        state: upgraded
        sudo_password: "{{ ansible_env.BECOME_PASSWORD }}"

    - name: Copy settings file
      when: not ansible_check_mode
      ansible.builtin.copy:
        src: "settings.brdgcBackup"
        dest: "{{ ansible_env.HOME }}/Downloads/settings.brdgcBackup"
        mode: '0644'

    - name: Open README
      ansible.builtin.import_role:
        name: misc_open_readme
      vars:
        misc_open_readme_rolename: install_bridgecast

    - name: Open BRIDGE CAST app
      ansible.builtin.command:
        cmd: /usr/bin/open --background -a 'BRIDGE CAST'
      changed_when: false
