---

- name: Install Visual Studio code & font
  block:
    - name: Install Cask app
      community.general.homebrew_cask:
        name:
          - font-jetbrains-mono-nerd-font
          - visual-studio-code
        state: upgraded

    - name: Install required tool/runtime
      community.general.homebrew:
        name:
          - ansible-lint
          - uv
          - volta

          # Go Tools: https://github.com/golang/vscode-go/wiki/tools
          - go@{{ install_vscode_go_version }}
          - dlv
          - gomodifytags
          - gopls
          - goreleaser
          - staticcheck
        state: upgraded

    - name: Install LTS Node.js
      ansible.builtin.command:
        cmd: /opt/homebrew/bin/volta install node@lts
      changed_when: false

    - name: Install latest extensions
      ansible.builtin.command:
        cmd: /opt/homebrew/bin/code --force --install-extension {{ item }}
      changed_when: false
      loop:
        - astro-build.astro-vscode
        - cocopon.iceberg-theme
        - gamunu.opentofu
        - github.copilot
        - github.vscode-github-actions
        - golang.go
        - hrst.yamaha-rt
        - hrst.yamaha-wlx
        - idleberg.applescript
        - ms-azuretools.vscode-docker
        - ms-ceintl.vscode-language-pack-ja
        - ms-kubernetes-tools.vscode-kubernetes-tools
        - ms-python.python
        - ms-vscode-remote.remote-containers
        - ms-vscode.hexeditor
        - redhat.ansible
        - redhat.vscode-yaml
        - sswg.swift-lang
        - stripe.markdoc-language-support
        - tamasfe.even-better-toml
        - tyriar.sort-lines
        - visualstudioexptteam.vscodeintellicode
        - vscode-icons-team.vscode-icons

    - name: Create conf directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ ansible_env.HOME }}/.config/git"
        - "{{ ansible_env.HOME }}/.config/zsh"
        - "{{ ansible_env.HOME }}/Library/Application Support/Code/User"

    - name: Copy Git/Go config files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        mode: '0644'
      loop:
        - { src: "go.zsh", dst: "{{ ansible_env.HOME }}/.config/zsh/go.zsh" }
        - { src: "vscode.gitconfig", dst: "{{ ansible_env.HOME }}/.config/git/vscode.gitconfig" }

    - name: Create VSCode config file
      when: not ansible_check_mode
      ansible.builtin.template:
        src: settings.json.j2
        dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/settings.json"
        mode: '0644'
