---

- name: Install Dell monitor driver
  block:
    - name: Tap custom repos
      check_mode: false
      community.general.homebrew_tap:
        name: legnoh/etc

    - name: Install driver app
      community.general.homebrew_cask:
        name:
          - dell-u4025qw-driver
          - dell-u4025qw-firmware-update-utility
        state: upgraded
        sudo_password: "{{ install_dell_monitor_driver_sudo_password }}"

    - name: Open README
      ansible.builtin.import_role:
        name: open_readme
      vars:
        open_readme_rolename: install_dell_monitor_driver
