---

- name: Install Private applications
  block:
    - name: Install Cask apps
      community.general.homebrew_cask:
        name: "{{ item }}"
        install_options: force
        state: upgraded
        sudo_password: "{{ install_private_casks_sudo_pass }}"
      loop:
        - betterzip
        - discord
        - obs # sudo required
      async: 10000
      poll: 0

    - name: Open README
      ansible.builtin.import_role:
        name: misc_open_readme
      vars:
        misc_open_readme_rolename: install_private_casks
