---

- name: Install Rancher Desktop
  block:
    - name: Install Rosetta2
      become: true
      ansible.builtin.command:
        cmd: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
      changed_when: false

    - name: Check Rancher Desktop was installed
      ansible.builtin.stat:
        path: "/Applications/Rancher\ Desktop.app"
      register: check_installed

    - name: Stop Rancher Desktop
      when: check_installed.stat.exists
      ansible.builtin.shell:
        cmd: >
          /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/rdctl --verbose shutdown
      changed_when: false

    - name: Install app
      community.general.homebrew_cask:
        name: rancher
        state: upgraded

    - name: Install docker-completion
      community.general.homebrew:
        name: docker-completion
        state: upgraded

    - name: Create config directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/zsh"
        state: directory
        mode: '0755'

    - name: Copy setting files
      when: not ansible_check_mode
      ansible.builtin.copy:
        src: rancher.zsh
        dest: "{{ ansible_env.HOME }}/.config/zsh/rancher.zsh"
        mode: '0644'

    - name: Create working-locked.json from template
      when: not ansible_check_mode
      ansible.builtin.template:
        src: working-locked.json.j2
        dest: /tmp/rancher-working-locked.json
        mode: '0644'

    # https://docs.rancherdesktop.io/how-to-guides/generating-deployment-profiles#generating-deployments
    - name: Create default profile
      ansible.builtin.shell:
        cmd: >
          /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/rdctl
          create-profile
          --output plist
          --input /tmp/rancher-working-locked.json
          > ~/Library/Preferences/io.rancherdesktop.profile.locked.plist
      changed_when: false

    - name: Start Rancher Desktop in background
      ansible.builtin.command:
        cmd: /usr/bin/open -a 'Rancher Desktop'
      changed_when: false

  # always:
  #   - name: Remove tempfile
  #     ansible.builtin.file:
  #       path: /tmp/rancher-working-locked.json
  #       state: absent
