---

- name: Install Git Packages
  block:
    - name: Install Git packages
      community.general.homebrew:
        name:
          - gh
          - ghq
          - gibo
          - git-lfs
        state: upgraded

    - name: Get my github profile
      ansible.builtin.uri:
        url: "https://api.github.com/users/{{ install_git_packages_github_username }}"
        status_code: 200
        body_format: json
        return_content: true
      register: github_profile

    - name: Get my github signing keys
      ansible.builtin.uri:
        url: "https://api.github.com/users/{{ install_git_packages_github_username }}/ssh_signing_keys"
        status_code: 200
        body_format: json
        return_content: true
      register: github_ssh_signing_keys

    - name: Copy Zsh config file
      ansible.builtin.import_role:
        name: misc_create_zshconf
      vars:
        misc_create_zshconf_src: ghq.zsh

    - name: Copy Gitconfig files
      ansible.builtin.include_role:
        name: misc_create_gitconf
      vars:
        misc_create_gitconf_src: "{{ item }}"
      loop:
        - common.gitconfig
        - credential.github.com.gitconfig
        - ghq.gitconfig
        - git-lfs.gitconfig
        - user.gitconfig.j2

    - name: Download global ignore file from gibo
      when: not ansible_check_mode
      ansible.builtin.shell:
        cmd: "gibo dump macOS VisualStudioCode > {{ ansible_env.HOME }}/.config/git/ignore"
      changed_when: false

    - name: Open README
      ansible.builtin.import_role:
        name: misc_open_readme
      vars:
        misc_open_readme_rolename: install_git_packages
