---

- name: Install Terminal config
  block:
    - name: Install font
      community.general.homebrew_cask:
        name: font-jetbrains-mono-nerd-font
        state: upgraded

    - name: Copy iceberg color theme file
      ansible.builtin.copy:
        src: iceberg.terminal
        dest: "/tmp/iceberg.terminal"
        mode: '0644'

    - name: Open with new theme
      ansible.builtin.command:
        cmd: /usr/bin/open --background -a Terminal "/tmp/iceberg.terminal"
      changed_when: false

    - name: Set default&startup theme
      ansible.builtin.command:
        cmd: /usr/bin/defaults write com.apple.Terminal "{{ item }} Window Settings" -string "iceberg"
      changed_when: false
      loop:
        - Default
        - Startup
