version: '3'

services:
  minio:
    image: minio/minio
    ports: ["9000:9000"]
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: 7dJQ6;Jy4o+g@X4VRMNijvp7&8,jRg^z6sumTx3g=nuqBrxYD9%U]A7ZKFpdz=MY
    command: server /export
