---
description: com.apple.finder
sudo: false
current_host: false
data:
  com.apple.finder:
    DesktopViewSettings:
      IconViewSettings:
        arrangeBy: kind
        gridSpacing: 1.0
        iconSize: 128.0
        labelOnBottom: true
        showItemInfo: true
        textSize: 14.0
    FXEnableExtensionsChangeWarning: false
    FXPreferredViewStyle: icnv
    NewWindowTarget: PfHm
    ShowPathbar: true
    ShowRecentTags: false
    ShowStatusBar: true
    SidebarWidth: 175
    WarnOnEmptyTrash: false
