---

- name: Set SSH configs
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ ansible_env.HOME }}/.config/ssh"
        - "{{ ansible_env.HOME }}/.ssh"

    - name: Create .ssh/config file
      when: not ansible_check_mode
      ansible.builtin.copy:
        src: ".ssh/config"
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        mode: '0644'
