brew 'awscli'
brew 'coreutils'
brew 'direnv'
brew 'ghq'
brew 'gibo'
brew 'go'
brew 'goreleaser'
brew 'jq'
brew 'mike-engel/jwt-cli/jwt-cli'
brew 'mas'
brew 'node'
brew 'ripgrep'
brew 'terminal-notifier'
brew 'tree'
brew 'uv'

cask '1password'
cask '1password-cli'
cask 'alfred'
cask 'betterzip'
cask 'legnoh/etc/dell-u4025qw-driver'
cask 'legnoh/etc/dell-u4025qw-firmware-update-utility'
cask 'fujitsu-scansnap-home'
cask 'google-chrome'
cask 'homebrew/cask-fonts/font-jetbrains-mono-nerd-font'
cask 'logi-options+'
cask 'monitorcontrol'
cask 'notion'
cask 'rancher'
cask 'rapidapi'
cask 'legnoh/etc/roland-bridge-cast-app'
cask 'visual-studio-code'
cask 'vlc'
cask 'zoom'

mas '1 Password for Safari', id:1569813296
mas 'Apple Developer', id:640199958
mas 'Copy Link to Pasteboard', id:1551527433
mas 'Keynote', id:409183694
mas 'Kindle', id:405399194
mas 'Numbers', id:409203825
mas 'OverPicture for Safari', id:1188020834
mas 'Pages', id:409201541
mas 'Pixelmator Pro', id:1289583905
mas 'PopClip', id:445189367
mas 'RSS Button for Safari', id:1437501942
mas 'Slack for Desktop', id:803453959
mas 'Userscripts', id:1463298887
mas 'Xcode', id:497799835
