brew 'awscli'
cask 'blackhole-2ch'
cask 'blackhole-16ch'
brew 'colordiff'
brew 'coreutils'
brew 'direnv'
brew 'fzf'
brew 'ghq'
brew 'gibo'
brew 'git'
brew 'go'
brew 'goreleaser'
brew 'jq'
brew 'kubernetes-cli'
brew 'kubernetes-helm'
brew 'kustomize'
brew 'mas'
brew 'node'
brew 'openssl'
brew 'pipenv'
brew 'python'
brew 'ripgrep'
brew 'smimesign'
brew 'stern'
brew 'terminal-notifier'
brew 'tree'
brew 'yarn'
brew 'yq'

cask '1password'
cask 'aerial'
cask 'alfred'
cask 'bettertouchtool'
cask 'docker'
cask 'homebrew/cask-drivers/shureplus-motiv'
cask 'homebrew/cask-fonts/font-jetbrains-mono'
cask 'notion'
cask 'paw'
cask 'visual-studio-code'
cask 'zoom'

mas '1 Password for Safari', id:1569813296
mas 'Copy Link to Pasteboard', id:1551527433
mas 'Keynote', id:409183694
mas 'Kindle', id:405399194
mas 'LadioCast', id:411213048
mas 'Meeter', id:1510445899
mas 'Numbers', id:409203825
mas 'OverPicture for Safari', id:1188020834
mas 'Pages', id:409201541
mas 'Pixelmator Pro', id:1289583905
mas 'PopClip', id:445189367
mas 'RSS Button for Safari', id:1437501942
mas 'Slack for Desktop', id:803453959
mas 'Tampermonkey', id:1482490089
mas 'Todoist', id:585829637
