# set volume for alarm
57 5 * * * osascript -e "set volume 60/100*7"

# daily update homebrew package
0 15 * * * /usr/local/bin/brew update && /usr/local/bin/brew cleanup
0 15 * * * /usr/local/bin/mas upgrade
0 16 * * * rm -rf /var/mail/$USER

# daily update ~/.gitignore
0 15 * * * /usr/local/bin/gibo update && /usr/local/bin/gibo dump macOS Linux JetBrains Vim > ~/.gitignore
1 15 * * * echo "\n.idea/workspace.xml" >> ~/.gitignore
