name: Bump Version(Node)

on:
  schedule:
    - cron: 0 4 * * 1
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      BREW_PKGNAME: node
      ROLE_VARFILE: roles/install_node/defaults/main.yml
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check LTS version
        id: lts
        env:
          EOL_PACKAGE_NAME: nodejs
          JQ_QUERY: "[.[] | select(.lts != false)] | .[0].cycle"
        run: |
          v=$(curl -s https://endoflife.date/api/${{ env.EOL_PACKAGE_NAME }}.json | jq -r "${{ env.JQ_QUERY }}")
          echo "GLOBAL: ${v}"
          echo "v=${v}" >> "$GITHUB_OUTPUT"

      - name: Check dotfiles version
        id: dot
        run: |
          v=$(yq -r ".install_${{ env.BREW_PKGNAME }}_version" ${{ env.ROLE_VARFILE }})
          echo "DOTFILE: ${v}"
          echo "v=${v}" >> "$GITHUB_OUTPUT"

      - name: Edit varfile
        if: steps.lts.outputs.v != steps.dot.outputs.v
        run: |
          yq e ".install_${{ env.BREW_PKGNAME }}_version=${{ steps.lts.outputs.v }}" -i ${{ env.ROLE_VARFILE }}

      - name: Get GitHub App Token
        uses: actions/create-github-app-token@v1
        id: github-app
        with:
          app-id: ${{ vars.G_BUMP_BOT_ID }}
          private-key: ${{ secrets.G_BUMP_BOT_PRIVATEKEY }}
          owner: ${{ github.repository_owner }}

      - name: Create bump PR
        if: steps.lts.outputs.v != steps.dot.outputs.v
        uses: peter-evans/create-pull-request@v7
        env:
          RELEASE_POLICY_URL: https://nodejs.org/en/about/previous-releases
          RELEASE_NOTES_URL: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V${{ steps.lts.outputs.v }}.md
        with:
          token: ${{ steps.github-app.outputs.token }}
          branch: ${{ env.BREW_PKGNAME }}-${{ steps.lts.outputs.v }}
          commit-message: "bump: ${{ env.BREW_PKGNAME }} v${{ steps.lts.outputs.v }}"
          sign-commits: true
          title: "bump: ${{ env.BREW_PKGNAME }} v${{ steps.lts.outputs.v }}"
          body: |
              - [Release Policy](${{ env.RELEASE_POLICY_URL }})
              - [Release Notes](${{ env.RELEASE_NOTES_URL }})
