name: Bump Version(Go)

on:
  schedule:
    - cron: 0 4 * * 1
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      BREW_PKGNAME: go
      ROLE_VARFILE: roles/install_vscode/defaults/main.yml
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check LTS version
        id: lts
        env:
          EOL_PACKAGE_NAME: go
          JQ_QUERY: ".[0].cycle"
        run: |
            LTS_VERSION_GLOBAL=$(curl -s https://endoflife.date/api/${EOL_PACKAGE_NAME}.json | jq -r "${{ env.JQ_QUERY }}")
            echo "LTS: ${LTS_VERSION_GLOBAL}"
            echo "v=${LTS_VERSION_GLOBAL}" >> "$GITHUB_OUTPUT"

      - name: Check dotfiles version
        id: dot
        run: |
            LTS_VERSION_DOTFILES=$(yq -r ".install_vscode_${BREW_PKGNAME}_version" ${ROLE_VARFILE})
            echo "DOTFILE: ${LTS_VERSION_DOTFILES}"
            echo "v=${LTS_VERSION_DOTFILES}" >> "$GITHUB_OUTPUT"

      - name: Edit varfile
        if: steps.lts.outputs.v != steps.dot.outputs.v
        run: |
          yq e ".install_vscode_${BREW_PKG_NAME}_version=${LTS_VERSION_GLOBAL}" -i ${ROLE_VARFILE}

      - name: Get GitHub App Token
        uses: actions/create-github-app-token@v1
        id: github-app
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Create bump PR
        if: steps.lts.outputs.v != steps.dot.outputs.v
        uses: peter-evans/create-pull-request@v7
        env:
          RELEASE_NOTES_URL: https://go.dev/doc/go${{ steps.lts.outputs.v }}
          RELEASE_POLICY_URL: https://go.dev/doc/devel/release#policy
        with:
          token: ${{ steps.github-app.outputs.token }}
          branch: ${{ env.BREW_PKGNAME }}-${{ steps.lts.outputs.v }}
          commit-message: "bump: ${BREW_PKGNAME} v${{ steps.lts.outputs.v }}"
          sign-commits: true
          title: "bump: ${BREW_PKGNAME} v${{ steps.lts.outputs.v }}"
          body: |
              - [Release Policy](${{ env.RELEASE_POLICY_URL }})
              - [Release Notes](${{ env.RELEASE_NOTES_URL }})
