name: Check brew bundle

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test(brew)
        run: brew bundle Brewfile.brew.rb
      - name: Test(cask)
        run: brew bundle Brewfile.cask.rb
