name: CI

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * 1

jobs:
  execute:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with: 
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install ansible
      run: brew install ansible

    - name: edit site.yml temporary
      run: sed -i '' 's/legnoh.dotfiles.//g' site.yml

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: site.yml
        options: --check
      env:
        BECOME_PASSWORD: dummy
