name: CI

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
  workflow_dispatch:

jobs:
  execute:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with: 
        ref: ${{ github.head_ref }}

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install ansible
      run: brew install ansible

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: site.yml
        options: --check
