name: Ansible Galaxy

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Edit galaxy.yml
      run: |
        export VERSION="${{ github.ref_name }}"
        envsubst < galaxy.yml.tpl > galaxy.yml

    - name: Deploy the collection
      uses: artis3n/ansible_galaxy_collection@v2
      with:
        api_key: ${{ secrets.GALAXY_API_KEY }}
